<div id="gradeBlock">
Grade: <strong><a href="/etextbooks/1">1</a> &#183; <a href="/etextbooks/2">2</a> &#183; <a href="/etextbooks/3">3</a> &#183; <a href="/etextbooks/4">4</a> &#183; <a href="/etextbooks/5">5</a> &#183; <a href="/etextbooks/6">6</a> &#183; <a href="/etextbooks/7">7</a> &#183; <a href="/etextbooks/8" class="ttip">8</a><div class="tooltip">
<?php if ($page['grade1']): ?>
    <?php print render($page['grade1']); ?>
<?php endif; ?></div> &#183; <a href="/etextbooks/9">9</a> &#183; <a href="/etextbooks/10">10</a> &#183; <a href="/etextbooks/11">11</a> &#183; <a href="/etextbooks/12">12</a></strong>
</div>